redis:
  image: redis:2.8
  hostname: core
  ports:
    - 6379

api:
  command: npm start
  image: docker.mydomain.com/api:latest
  ports:
    - 3000
  environment:
    VIRTUAL_PORT: 3000
    VIRTUAL_HOST: api.mydomain.com
    NODE_ENV: development
    MONGO_DATABASE: develop_api
  volumes:
    - .:/src
  links:
    - 'redis:redis'
  env_file:
    - .db
    - .mq

app:
  image: docker.mydomain.com/app:latest
  ports:
    - 80
  environment:
    VIRTUAL_HOST: app.mydomain.com
    VIRTUAL_PORT: 80
    NODE_ENV: production
    API_URL: http://api.mydomain.com
  privileged: True
